-- *********************************** SqlDBM: Databricks ***********************************
-- * Generated by SqlDBM: EasyJet Sample Physical Project by hazal.sener+easyjet@sqldbm.com *




-- ************************************** PassengerBookingData.Passenger
CREATE TABLE PassengerBookingData.Passenger
(
 PassengerID     int NOT NULL CONSTRAINT PK_Passenger PRIMARY KEY,
 FirstName       string,
 LastName        string,
 Email           string,
 Phone           string,
 DateOfBirth     date,
 Nationality     string,
 Gender          string,
 FrequentFlyerID string,
 Address         string
);



-- ************************************** CustomerProfile.LoyaltyProgram
CREATE TABLE CustomerProfile.LoyaltyProgram
(
 LoyaltyProgramID int NOT NULL CONSTRAINT PK_LoyaltyProgram PRIMARY KEY,
 ProgramName      string,
 PointsRequired   int,
 Description      string
);



-- ************************************** Holidays.holiday_packages
CREATE TABLE Holidays.holiday_packages
(
 package_id          string NOT NULL CONSTRAINT PK_holiday_packages PRIMARY KEY,
 package_name        string NOT NULL,
 description         string,
 departure_airport   string NOT NULL,
 destination_airport string NOT NULL,
 start_date          timestamp NOT NULL,
 end_date            timestamp NOT NULL,
 total_price         decimal(10, 2) NOT NULL
)
USING DELTA;



-- ************************************** CapacityManagement.flights
CREATE TABLE CapacityManagement.flights
(
 flight_id       string NOT NULL CONSTRAINT PK_flights PRIMARY KEY,
 flight_number   string NOT NULL,
 departure_date  timestamp NOT NULL,
 arrival_date    timestamp NOT NULL,
 origin          string NOT NULL,
 destination     string NOT NULL,
 total_seats     int NOT NULL,
 available_seats int NOT NULL
)
USING DELTA;



-- ************************************** PassengerBookingData.Flight
CREATE TABLE PassengerBookingData.Flight
(
 FlightID      int NOT NULL CONSTRAINT PK_Flight PRIMARY KEY,
 FlightNumber  string,
 Origin        string,
 Destination   string,
 DepartureTime timestamp,
 ArrivalTime   timestamp,
 AircraftType  string,
 Duration      int,
 Distance      int,
 Status        string
);



-- ************************************** EsgData.esg_strategy
CREATE TABLE EsgData.esg_strategy
(
 strategy_id         string NOT NULL CONSTRAINT PK_esg_strategy PRIMARY KEY,
 strategy_name       string NOT NULL,
 description         string,
 start_date          timestamp NOT NULL,
 end_date            timestamp,
 primary_goals       string,
 performance_metrics string
)
USING DELTA;



-- ************************************** EsgData.esg_reporting_frameworks
CREATE TABLE EsgData.esg_reporting_frameworks
(
 framework_id        string NOT NULL CONSTRAINT PK_esg_reporting_frameworks PRIMARY KEY,
 framework_name      string NOT NULL,
 description         string,
 last_updated        timestamp NOT NULL,
 compliance_required boolean NOT NULL
)
USING DELTA;



-- ************************************** Environmental.emission_sources
CREATE TABLE Environmental.emission_sources
(
 source_id        string NOT NULL CONSTRAINT PK_emission_sources PRIMARY KEY,
 source_name      string NOT NULL,
 category         string NOT NULL,
 emissions_factor decimal(10, 5) NOT NULL,
 measurement_unit string NOT NULL
)
USING DELTA;



-- ************************************** FlightOpsScheduling.CrewMember
CREATE TABLE FlightOpsScheduling.CrewMember
(
 CrewMemberID      int NOT NULL CONSTRAINT PK_CrewMember PRIMARY KEY,
 FirstName         string,
 LastName          string,
 `Position`        string,
 LicenseNumber     string,
 LicenseExpiryDate date,
 ContactInfo       string,
 ExperienceYears   int,
 Nationality       string,
 DateOfBirth       date
);



-- ************************************** Aircraft.capacity_forecasts
CREATE TABLE Aircraft.capacity_forecasts
(
 forecast_id        string NOT NULL CONSTRAINT PK_capacity_forecasts PRIMARY KEY,
 forecast_date      timestamp NOT NULL,
 projected_capacity int NOT NULL,
 forecasted_flights int NOT NULL,
 forecasted_revenue decimal(15, 2) NOT NULL,
 assumptions        string
)
USING DELTA;



-- ************************************** FinancialPerformance.AnnualFinancialSummary
CREATE TABLE FinancialPerformance.AnnualFinancialSummary
(
 SummaryID     int NOT NULL CONSTRAINT PK_AnnualFinancialSummary PRIMARY KEY,
 `Year`        int,
 TotalRevenue  decimal(10, 2),
 TotalExpenses decimal(10, 2),
 TotalProfit   decimal(10, 2)
);



-- ************************************** AncillaryRevenue.ancillary_revenue_trends
CREATE TABLE AncillaryRevenue.ancillary_revenue_trends
(
 trend_id        string NOT NULL CONSTRAINT PK_ancillary_revenue_trends PRIMARY KEY,
 `year`          int NOT NULL,
 monthly_revenue array<decimal>,
 total_revenue   decimal(10, 2) NOT NULL
)
USING DELTA;



-- ************************************** AncillaryRevenue.ancillary_revenue_streams
CREATE TABLE AncillaryRevenue.ancillary_revenue_streams
(
 revenue_stream_id string NOT NULL CONSTRAINT PK_ancillary_revenue_streams PRIMARY KEY,
 stream_name       string NOT NULL,
 description       string,
 `year`            int NOT NULL,
 total_revenue     decimal(10, 2) NOT NULL,
 growth_rate       decimal(5, 2) NOT NULL
)
USING DELTA;



-- ************************************** Aircraft.aircraft_types
CREATE TABLE Aircraft.aircraft_types
(
 aircraft_type_id string NOT NULL,
 manufacturer     string NOT NULL,
 model            string NOT NULL,
 capacity         int NOT NULL
);



-- ************************************** Aircraft.aircraft_orders
CREATE TABLE Aircraft.aircraft_orders
(
 order_id               string NOT NULL CONSTRAINT PK_aircraft_orders PRIMARY KEY,
 aircraft_type_id       string NOT NULL,
 order_date             timestamp NOT NULL,
 expected_delivery_date timestamp NOT NULL,
 order_status           string NOT NULL,
 quantity               int NOT NULL,
 vendor                 string NOT NULL
)
USING DELTA;



-- ************************************** Aircraft.aircraft_fleet
CREATE TABLE Aircraft.aircraft_fleet
(
 aircraft_id           string NOT NULL CONSTRAINT PK_aircraft_fleet PRIMARY KEY,
 aircraft_type_id      string NOT NULL,
 registration_number   string NOT NULL,
 acquisition_date      timestamp NOT NULL,
 status                string NOT NULL,
 last_maintenance_date timestamp,
 next_maintenance_date timestamp,
 asset_value           decimal(15, 2) NOT NULL
)
USING DELTA;



-- ************************************** FlightOpsScheduling.Aircraft
CREATE TABLE FlightOpsScheduling.Aircraft
(
 AircraftID          int NOT NULL CONSTRAINT PK_Aircraft PRIMARY KEY,
 AircraftType        string,
 Capacity            int,
 Manufacturer        string,
 YearOfManufacture   int,
 RegistrationNumber  string,
 Status              string,
 LastMaintenanceDate date,
 TotalFlightHours    int,
 FuelCapacity        decimal(10, 2)
);



-- ************************************** CapacityManagement.seat_availability
CREATE TABLE CapacityManagement.seat_availability
(
 seat_id      string NOT NULL CONSTRAINT PK_seat_availability PRIMARY KEY,
 flight_id    string NOT NULL CONSTRAINT FK_seat_availability_flight REFERENCES CapacityManagement.flights,
 seat_number  string NOT NULL,
 seat_class   string NOT NULL,
 is_available boolean NOT NULL
)
USING DELTA;



-- ************************************** CapacityManagement.reservations
CREATE TABLE CapacityManagement.reservations
(
 reservation_id   string NOT NULL CONSTRAINT PK_reservations PRIMARY KEY,
 passenger_id     string NOT NULL,
 flight_id        string NOT NULL CONSTRAINT FK_reservations_flight REFERENCES CapacityManagement.flights,
 reservation_date timestamp NOT NULL,
 status           string NOT NULL
)
USING DELTA;



-- ************************************** PassengerBookingData.PassengerPreferences
CREATE TABLE PassengerBookingData.PassengerPreferences
(
 PreferenceID      int NOT NULL CONSTRAINT PK_PassengerPreferences PRIMARY KEY,
 PassengerID       int CONSTRAINT FK_PassengerPreferences_1 REFERENCES PassengerBookingData.Passenger,
 SeatPreference    string,
 MealPreference    string,
 SpecialAssistance boolean,
 PreferredLanguage string
);



-- ************************************** AncillaryRevenue.passenger_ancillary_purchases
CREATE TABLE AncillaryRevenue.passenger_ancillary_purchases
(
 purchase_id       string NOT NULL CONSTRAINT PK_passenger_ancillary_purchases PRIMARY KEY,
 passenger_id      string NOT NULL,
 revenue_stream_id string NOT NULL CONSTRAINT FK_passenger_ancillary_purchases_1 REFERENCES AncillaryRevenue.ancillary_revenue_streams,
 purchase_date     timestamp NOT NULL,
 purchase_amount   decimal(10, 2) NOT NULL
)
USING DELTA;



-- ************************************** FlightOpsScheduling.MaintenanceSchedule
CREATE TABLE FlightOpsScheduling.MaintenanceSchedule
(
 MaintenanceID      int NOT NULL CONSTRAINT PK_MaintenanceSchedule PRIMARY KEY,
 AircraftID         int CONSTRAINT FK_MaintenanceSchedule_1 REFERENCES FlightOpsScheduling.Aircraft,
 MaintenanceType    string,
 ScheduledDate      date,
 CompletionDate     date,
 Status             string,
 Cost               decimal(10, 2),
 Description        string,
 NextMaintenanceDue date
);



-- ************************************** Aircraft.maintenance_records
CREATE TABLE Aircraft.maintenance_records
(
 maintenance_id   string NOT NULL CONSTRAINT PK_maintenance_records PRIMARY KEY,
 aircraft_id      string NOT NULL CONSTRAINT FK_maintenance_records_1 REFERENCES Aircraft.aircraft_fleet,
 maintenance_date timestamp NOT NULL,
 maintenance_type string NOT NULL,
 maintenance_cost decimal(10, 2) NOT NULL,
 description      string
)
USING DELTA;



-- ************************************** CapacityManagement.load_factors
CREATE TABLE CapacityManagement.load_factors
(
 load_factor_id string NOT NULL CONSTRAINT PK_load_factors PRIMARY KEY,
 flight_id      string NOT NULL CONSTRAINT FK_load_factors_flight REFERENCES CapacityManagement.flights,
 month          string NOT NULL,
 `year`         int NOT NULL,
 load_factor    decimal(5, 2) NOT NULL
)
USING DELTA;



-- ************************************** Holidays.holiday_package_reviews
CREATE TABLE Holidays.holiday_package_reviews
(
 review_id    string NOT NULL CONSTRAINT PK_87 PRIMARY KEY,
 passenger_id string NOT NULL,
 review_date  timestamp NOT NULL,
 rating       int NOT NULL,
 package_id   string NOT NULL CONSTRAINT FK_75 REFERENCES Holidays.holiday_packages
);



-- ************************************** Holidays.holiday_package_pricing
CREATE TABLE Holidays.holiday_package_pricing
(
 pricing_id     string NOT NULL CONSTRAINT PK_holiday_package_pricing PRIMARY KEY,
 package_id     string NOT NULL CONSTRAINT FK_holiday_package_pricing_1 REFERENCES Holidays.holiday_packages,
 price          decimal(10, 2) NOT NULL,
 effective_date timestamp NOT NULL
)
USING DELTA;



-- ************************************** Holidays.holiday_package_itineraries
CREATE TABLE Holidays.holiday_package_itineraries
(
 itinerary_id     string NOT NULL CONSTRAINT PK_holiday_package_itineraries PRIMARY KEY,
 package_id       string NOT NULL CONSTRAINT FK_holiday_package_itineraries_1 REFERENCES Holidays.holiday_packages,
 flight_id        string NOT NULL,
 stopover_airport string,
 stopover_time    timestamp
)
USING DELTA;



-- ************************************** Holidays.holiday_package_bookings
CREATE TABLE Holidays.holiday_package_bookings
(
 booking_id   string NOT NULL CONSTRAINT PK_holiday_package_bookings PRIMARY KEY,
 package_id   string NOT NULL CONSTRAINT FK_holiday_package_bookings_1 REFERENCES Holidays.holiday_packages,
 passenger_id string NOT NULL,
 booking_date timestamp NOT NULL,
 total_price  decimal(10, 2) NOT NULL
)
USING DELTA;



-- ************************************** EsgData.governance_compliance
CREATE TABLE EsgData.governance_compliance
(
 governance_id     string NOT NULL CONSTRAINT PK_governance_compliance PRIMARY KEY,
 framework_id      string NOT NULL CONSTRAINT FK_governance_compliance_1 REFERENCES EsgData.esg_reporting_frameworks,
 compliance_status string NOT NULL,
 last_review_date  timestamp,
 next_review_date  timestamp,
 compliance_notes  string
)
USING DELTA;



-- ************************************** Aircraft.fuel_consumption
CREATE TABLE Aircraft.fuel_consumption
(
 fuel_id       string NOT NULL CONSTRAINT PK_fuel_consumption PRIMARY KEY,
 aircraft_id   string NOT NULL CONSTRAINT FK_fuel_consumption_1 REFERENCES Aircraft.aircraft_fleet,
 date          timestamp NOT NULL,
 fuel_quantity decimal(10, 2) NOT NULL,
 flight_hours  decimal(10, 2) NOT NULL
)
USING DELTA;



-- ************************************** FlightOpsScheduling.FlightSchedule
CREATE TABLE FlightOpsScheduling.FlightSchedule
(
 FlightID           int NOT NULL CONSTRAINT PK_FlightSchedule PRIMARY KEY,
 DepartureAirport   string,
 ArrivalAirport     string,
 ScheduledDeparture timestamp,
 ScheduledArrival   timestamp,
 AircraftID         int CONSTRAINT FK_FlightSchedule_1 REFERENCES FlightOpsScheduling.Aircraft,
 Status             string,
 Distance           int,
 Duration           int,
 FlightNumber       string
);



-- ************************************** CapacityManagement.fare_classes
CREATE TABLE CapacityManagement.fare_classes
(
 fare_class_id   string NOT NULL CONSTRAINT PK_fare_classes PRIMARY KEY,
 flight_id       string NOT NULL CONSTRAINT FK_fare_classes_flight REFERENCES CapacityManagement.flights,
 fare_class_name string NOT NULL
)
USING DELTA;



-- ************************************** Environmental.energy_consumption
CREATE TABLE Environmental.energy_consumption
(
 consumption_id      string NOT NULL CONSTRAINT PK_energy_consumption PRIMARY KEY,
 report_date         timestamp NOT NULL,
 total_energy        decimal(10, 2) NOT NULL,
 source_id           string NOT NULL CONSTRAINT FK_energy_consumption_1 REFERENCES Environmental.emission_sources,
 emissions_generated decimal(10, 2)
)
USING DELTA;



-- ************************************** Environmental.emission_reports
CREATE TABLE Environmental.emission_reports
(
 report_id            string NOT NULL CONSTRAINT PK_emission_reports PRIMARY KEY,
 report_date          timestamp NOT NULL,
 total_emissions      decimal(10, 2) NOT NULL,
 source_id            string NOT NULL CONSTRAINT FK_emission_reports_1 REFERENCES Environmental.emission_sources,
 reduction_percentage decimal(5, 2),
 comments             string
)
USING DELTA;



-- ************************************** Aircraft.depreciation_schedule
CREATE TABLE Aircraft.depreciation_schedule
(
 depreciation_id          string NOT NULL CONSTRAINT PK_depreciation_schedule PRIMARY KEY,
 aircraft_id              string NOT NULL CONSTRAINT FK_depreciation_schedule_1 REFERENCES Aircraft.aircraft_fleet,
 start_date               timestamp NOT NULL,
 end_date                 timestamp NOT NULL,
 depreciation_rate        decimal(5, 2) NOT NULL,
 accumulated_depreciation decimal(15, 2) NOT NULL,
 current_value            decimal(15, 2) NOT NULL
)
USING DELTA;



-- ************************************** AncillaryRevenue.customer_feedback
CREATE TABLE AncillaryRevenue.customer_feedback
(
 feedback_id       string NOT NULL CONSTRAINT PK_87_1 PRIMARY KEY,
 passenger_id      string NOT NULL,
 feedback_date     timestamp NOT NULL,
 rating            int NOT NULL,
 revenue_stream_id string NOT NULL CONSTRAINT FK_77 REFERENCES AncillaryRevenue.ancillary_revenue_streams
);



-- ************************************** CustomerProfile.Customer
CREATE TABLE CustomerProfile.Customer
(
 CustomerID       int NOT NULL CONSTRAINT PK_Customer PRIMARY KEY,
 FirstName        string,
 LastName         string,
 Email            string,
 Phone            string,
 DateOfBirth      date,
 Nationality      string,
 Gender           string,
 Address          string,
 LoyaltyProgramID int CONSTRAINT FK_Customer_1 REFERENCES CustomerProfile.LoyaltyProgram
);



-- ************************************** FinancialPerformance.CostTracking
CREATE TABLE FinancialPerformance.CostTracking
(
 CostID       int NOT NULL CONSTRAINT PK_CostTracking PRIMARY KEY,
 Department   string,
 Amount       decimal(10, 2),
 DateIncurred date,
 Description  string,
 SummaryID    int CONSTRAINT FK_CostTracking_AnnualSummary REFERENCES FinancialPerformance.AnnualFinancialSummary
);



-- ************************************** CapacityManagement.capacity_management
CREATE TABLE CapacityManagement.capacity_management
(
 capacity_id     string NOT NULL CONSTRAINT PK_capacity_management PRIMARY KEY,
 flight_id       string NOT NULL CONSTRAINT FK_capacity_management_flight REFERENCES CapacityManagement.flights,
 total_seats     int NOT NULL,
 available_seats int NOT NULL,
 load_factor     decimal(5, 2) NOT NULL
)
USING DELTA;



-- ************************************** FinancialPerformance.BusinessUnitPerformance
CREATE TABLE FinancialPerformance.BusinessUnitPerformance
(
 UnitID    int NOT NULL CONSTRAINT PK_BusinessUnitPerformance PRIMARY KEY,
 UnitName  string,
 Revenue   decimal(10, 2),
 Costs     decimal(10, 2),
 Profit    decimal(10, 2),
 SummaryID int CONSTRAINT FK_BusinessUnitPerformance_AnnualSummary REFERENCES FinancialPerformance.AnnualFinancialSummary
);



-- ************************************** PassengerBookingData.Booking
CREATE TABLE PassengerBookingData.Booking
(
 BookingID      int NOT NULL CONSTRAINT PK_Booking PRIMARY KEY,
 PassengerID    int CONSTRAINT FK_Booking_1 REFERENCES PassengerBookingData.Passenger,
 FlightID       int CONSTRAINT FK_Booking_2 REFERENCES PassengerBookingData.Flight,
 BookingDate    timestamp,
 TotalAmount    decimal(10, 2),
 BookingChannel string,
 BookingStatus  string,
 PaymentMethod  string,
 Currency       string
);



-- ************************************** AncillaryRevenue.ancillary_revenue_transactions
CREATE TABLE AncillaryRevenue.ancillary_revenue_transactions
(
 transaction_id    string NOT NULL CONSTRAINT PK_ancillary_revenue_transactions PRIMARY KEY,
 revenue_stream_id string NOT NULL CONSTRAINT FK_ancillary_revenue_transactions_1 REFERENCES AncillaryRevenue.ancillary_revenue_streams,
 passenger_id      string NOT NULL,
 transaction_date  timestamp NOT NULL,
 amount            decimal(10, 2) NOT NULL
)
USING DELTA;



-- ************************************** AncillaryRevenue.ancillary_revenue_analysis
CREATE TABLE AncillaryRevenue.ancillary_revenue_analysis
(
 analysis_id       string NOT NULL CONSTRAINT PK_ancillary_revenue_analysis PRIMARY KEY,
 `year`            int NOT NULL,
 total_revenue     decimal(10, 2) NOT NULL,
 comparison_year   int NOT NULL,
 growth_percentage decimal(5, 2) NOT NULL,
 revenue_stream_id string NOT NULL CONSTRAINT FK_76 REFERENCES AncillaryRevenue.ancillary_revenue_streams,
 trend_id          string NOT NULL CONSTRAINT FK_79 REFERENCES AncillaryRevenue.ancillary_revenue_trends
)
USING DELTA;



-- ************************************** AncillaryRevenue.ancillary_promotions
CREATE TABLE AncillaryRevenue.ancillary_promotions
(
 promotion_id      string NOT NULL CONSTRAINT PK_ancillary_promotions PRIMARY KEY,
 revenue_stream_id string NOT NULL CONSTRAINT FK_ancillary_promotions_1 REFERENCES AncillaryRevenue.ancillary_revenue_streams,
 promotion_name    string NOT NULL,
 discount_rate     decimal(5, 2) NOT NULL,
 start_date        timestamp NOT NULL,
 end_date          timestamp NOT NULL
)
USING DELTA;



-- ************************************** Aircraft.aircraft_utilization
CREATE TABLE Aircraft.aircraft_utilization
(
 utilization_id     string NOT NULL CONSTRAINT PK_aircraft_utilization PRIMARY KEY,
 aircraft_id        string NOT NULL CONSTRAINT FK_aircraft_utilization_1 REFERENCES Aircraft.aircraft_fleet,
 date               timestamp NOT NULL,
 hours_flown        decimal(10, 2) NOT NULL,
 flights_operated   int NOT NULL,
 passengers_carried int NOT NULL
)
USING DELTA;



-- ************************************** Aircraft.aircraft_purchases
CREATE TABLE Aircraft.aircraft_purchases
(
 purchase_id    string NOT NULL CONSTRAINT PK_aircraft_purchases PRIMARY KEY,
 aircraft_id    string NOT NULL CONSTRAINT FK_aircraft_purchases_1 REFERENCES Aircraft.aircraft_fleet,
 purchase_date  timestamp NOT NULL,
 purchase_price decimal(15, 2) NOT NULL,
 delivery_date  timestamp NOT NULL,
 vendor         string NOT NULL
)
USING DELTA;



-- ************************************** Aircraft.aircraft_performance_metrics
CREATE TABLE Aircraft.aircraft_performance_metrics
(
 performance_id               string NOT NULL CONSTRAINT PK_aircraft_performance_metrics PRIMARY KEY,
 aircraft_id                  string NOT NULL CONSTRAINT FK_aircraft_performance_metrics_1 REFERENCES Aircraft.aircraft_fleet,
 date                         timestamp NOT NULL,
 on_time_departure_percentage decimal(5, 2) NOT NULL,
 fuel_efficiency              decimal(10, 2) NOT NULL,
 primary_seat_capacity        int NOT NULL
)
USING DELTA;



-- ************************************** Aircraft.aircraft_lifecycle_management
CREATE TABLE Aircraft.aircraft_lifecycle_management
(
 lifecycle_id string NOT NULL CONSTRAINT PK_aircraft_lifecycle_management PRIMARY KEY,
 aircraft_id  string NOT NULL CONSTRAINT FK_aircraft_lifecycle_management_1 REFERENCES Aircraft.aircraft_fleet,
 stage        string NOT NULL,
 start_date   timestamp NOT NULL,
 end_date     timestamp,
 notes        string
)
USING DELTA;



-- ************************************** PassengerBookingData.Ticket
CREATE TABLE PassengerBookingData.Ticket
(
 TicketID         int NOT NULL CONSTRAINT PK_Ticket PRIMARY KEY,
 BookingID        int CONSTRAINT FK_Ticket_1 REFERENCES PassengerBookingData.Booking,
 SeatNumber       string,
 TicketPrice      decimal(10, 2),
 TicketStatus     string,
 FareClass        string,
 CheckInStatus    string,
 BaggageAllowance int,
 MealPreference   string
);



-- ************************************** Environmental.sustainability_metrics
CREATE TABLE Environmental.sustainability_metrics
(
 metric_id        string NOT NULL CONSTRAINT PK_sustainability_metrics PRIMARY KEY,
 metric_name      string NOT NULL,
 metric_value     decimal(10, 2) NOT NULL,
 measurement_unit string NOT NULL,
 report_date      timestamp NOT NULL,
 consumption_id   string NOT NULL CONSTRAINT FK_56 REFERENCES Environmental.energy_consumption
)
USING DELTA;



-- ************************************** FinancialPerformance.RevenueTracking
CREATE TABLE FinancialPerformance.RevenueTracking
(
 RevenueID    int NOT NULL CONSTRAINT PK_RevenueTracking PRIMARY KEY,
 FlightID     int CONSTRAINT FK_RevenueTracking_FlightSchedule REFERENCES FlightOpsScheduling.FlightSchedule,
 RevenueType  string,
 Amount       decimal(10, 2),
 DateRecorded date,
 SummaryID    int CONSTRAINT FK_RevenueTracking_AnnualSummary REFERENCES FinancialPerformance.AnnualFinancialSummary
);



-- ************************************** CustomerProfile.PromotionParticipation
CREATE TABLE CustomerProfile.PromotionParticipation
(
 ParticipationID   int NOT NULL CONSTRAINT PK_PromotionParticipation PRIMARY KEY,
 CustomerID        int CONSTRAINT FK_PromotionParticipation_1 REFERENCES CustomerProfile.Customer,
 PromotionID       int,
 ParticipationDate date
);



-- ************************************** FinancialPerformance.ProfitPerSeat
CREATE TABLE FinancialPerformance.ProfitPerSeat
(
 ProfitID          int NOT NULL CONSTRAINT PK_ProfitPerSeat PRIMARY KEY,
 FlightID          int CONSTRAINT FK_ProfitPerSeat_FlightSchedule REFERENCES FlightOpsScheduling.FlightSchedule,
 Revenue           decimal(10, 2),
 OperationalCost   decimal(10, 2),
 Profit            decimal(10, 2),
 ProfitMargin      decimal(5, 2),
 DateOfCalculation date,
 SummaryID         int CONSTRAINT FK_ProfitPerSeat_AnnualSummary REFERENCES FinancialPerformance.AnnualFinancialSummary
);



-- ************************************** FinancialPerformance.OperationalExpenses
CREATE TABLE FinancialPerformance.OperationalExpenses
(
 ExpenseID    int NOT NULL CONSTRAINT PK_OperationalExpenses PRIMARY KEY,
 FlightID     int CONSTRAINT FK_OperationalExpenses_FlightSchedule REFERENCES FlightOpsScheduling.FlightSchedule,
 ExpenseType  string,
 Amount       decimal(10, 2),
 Description  string,
 DateIncurred date,
 SummaryID    int CONSTRAINT FK_OperationalExpenses_AnnualSummary REFERENCES FinancialPerformance.AnnualFinancialSummary
);



-- ************************************** CustomerProfile.LoyaltyPoints
CREATE TABLE CustomerProfile.LoyaltyPoints
(
 PointsID       int NOT NULL CONSTRAINT PK_LoyaltyPoints PRIMARY KEY,
 CustomerID     int CONSTRAINT FK_LoyaltyPoints_2 REFERENCES CustomerProfile.Customer,
 PointsEarned   int,
 PointsRedeemed int,
 Balance        int,
 LastUpdated    date
);



-- ************************************** FlightOpsScheduling.FlightStatusHistory
CREATE TABLE FlightOpsScheduling.FlightStatusHistory
(
 StatusID         int NOT NULL CONSTRAINT PK_FlightStatusHistory PRIMARY KEY,
 FlightID         int CONSTRAINT FK_FlightStatusHistory_1 REFERENCES FlightOpsScheduling.FlightSchedule,
 StatusChangeDate timestamp,
 OldStatus        string,
 NewStatus        string,
 Remarks          string
);



-- ************************************** FlightOpsScheduling.FlightRoute
CREATE TABLE FlightOpsScheduling.FlightRoute
(
 RouteID         int NOT NULL CONSTRAINT PK_FlightRoute PRIMARY KEY,
 FlightID        int CONSTRAINT FK_FlightRoute_1 REFERENCES FlightOpsScheduling.FlightSchedule,
 Origin          string,
 Destination     string,
 Distance        int,
 Duration        int,
 LayoverDuration int
);



-- ************************************** CustomerProfile.FlightHistory
CREATE TABLE CustomerProfile.FlightHistory
(
 HistoryID   int NOT NULL CONSTRAINT PK_FlightHistory PRIMARY KEY,
 CustomerID  int CONSTRAINT FK_FlightHistory_1 REFERENCES CustomerProfile.Customer,
 FlightID    int CONSTRAINT FK_FlightHistory_2 REFERENCES FlightOpsScheduling.FlightSchedule, CONSTRAINT FK_FlightHistory_4 FOREIGN KEY (FlightID) REFERENCES FlightOpsScheduling.FlightSchedule,
 BookingDate timestamp,
 TravelDate  date,
 FareClass   string
);



-- ************************************** CustomerAnalytics.FeedbackAnalysis
CREATE TABLE CustomerAnalytics.FeedbackAnalysis
(
 AnalysisID            int NOT NULL CONSTRAINT PK_FeedbackAnalysis PRIMARY KEY,
 CustomerID            int CONSTRAINT FK_FeedbackAnalysis_Customer REFERENCES CustomerProfile.Customer,
 AnalysisDate          date,
 PositiveFeedbackCount int,
 NegativeFeedbackCount int,
 SentimentScore        decimal(5, 2)
);



-- ************************************** CustomerProfile.CustomerPreferences
CREATE TABLE CustomerProfile.CustomerPreferences
(
 PreferenceID      int NOT NULL CONSTRAINT PK_CustomerPreferences PRIMARY KEY,
 CustomerID        int CONSTRAINT FK_CustomerPreferences_2 REFERENCES CustomerProfile.Customer,
 SeatPreference    string,
 MealPreference    string,
 SpecialAssistance boolean
);



-- ************************************** CustomerProfile.CustomerFeedback
CREATE TABLE CustomerProfile.CustomerFeedback
(
 FeedbackID   int NOT NULL CONSTRAINT PK_CustomerFeedback PRIMARY KEY,
 CustomerID   int CONSTRAINT FK_CustomerFeedback_1 REFERENCES CustomerProfile.Customer,
 FlightID     int CONSTRAINT FK_CustomerFeedback_2 REFERENCES FlightOpsScheduling.FlightSchedule, CONSTRAINT FK_CustomerFeedback_4 FOREIGN KEY (FlightID) REFERENCES FlightOpsScheduling.FlightSchedule,
 FeedbackDate date,
 Rating       int,
 Comments     string
);



-- ************************************** FlightOpsScheduling.CrewAssignment
CREATE TABLE FlightOpsScheduling.CrewAssignment
(
 AssignmentID   int NOT NULL CONSTRAINT PK_CrewAssignment PRIMARY KEY,
 FlightID       int CONSTRAINT FK_CrewAssignment_1 REFERENCES FlightOpsScheduling.FlightSchedule,
 CrewMemberID   int CONSTRAINT FK_CrewAssignment_2 REFERENCES FlightOpsScheduling.CrewMember,
 AssignmentDate date,
 DutyStartTime  timestamp,
 DutyEndTime    timestamp
);



-- ************************************** Environmental.carbon_offsetting_programs
CREATE TABLE Environmental.carbon_offsetting_programs
(
 program_id    string NOT NULL CONSTRAINT PK_carbon_offsetting_programs PRIMARY KEY,
 program_name  string NOT NULL,
 description   string,
 offset_amount decimal(10, 2) NOT NULL,
 start_date    timestamp NOT NULL,
 end_date      timestamp,
 status        string NOT NULL,
 report_id     string NOT NULL CONSTRAINT FK_58 REFERENCES Environmental.emission_reports
)
USING DELTA;



-- ************************************** AncillaryRevenueTracking.AncillaryRevenue
CREATE TABLE AncillaryRevenueTracking.AncillaryRevenue
(
 AncillaryID           int NOT NULL CONSTRAINT PK_AncillaryRevenue PRIMARY KEY,
 BookingID             int CONSTRAINT FK_AncillaryRevenue_1 REFERENCES PassengerBookingData.Booking,
 SeatUpgradeFee        decimal(10, 2),
 BaggageFee            decimal(10, 2),
 MealFee               decimal(10, 2),
 InsuranceFee          decimal(10, 2),
 TotalAncillaryRevenue decimal(10, 2),
 Currency              string
);



-- ************************************** AncillaryRevenue.ancillary_revenue_reports
CREATE TABLE AncillaryRevenue.ancillary_revenue_reports
(
 report_id     string NOT NULL CONSTRAINT PK_ancillary_revenue_reports PRIMARY KEY,
 `year`        int NOT NULL,
 total_revenue decimal(10, 2) NOT NULL,
 report_date   timestamp NOT NULL,
 analysis_id   string NOT NULL CONSTRAINT FK_80 REFERENCES AncillaryRevenue.ancillary_revenue_analysis
)
USING DELTA;



-- ************************************** PassengerBookingData.TicketHistory
CREATE TABLE PassengerBookingData.TicketHistory
(
 HistoryID         int NOT NULL CONSTRAINT PK_TicketHistory PRIMARY KEY,
 TicketID          int CONSTRAINT FK_TicketHistory_1 REFERENCES PassengerBookingData.Ticket,
 ChangeDate        timestamp,
 ChangeDescription string,
 StatusBefore      string,
 StatusAfter       string
);



-- ************************************** Environmental.sustainability_goals
CREATE TABLE Environmental.sustainability_goals
(
 goal_id      string NOT NULL CONSTRAINT PK_sustainability_goals PRIMARY KEY,
 goal_name    string NOT NULL,
 description  string,
 target_year  int NOT NULL,
 progress     decimal(5, 2) NOT NULL,
 last_updated timestamp NOT NULL,
 program_id   string NOT NULL CONSTRAINT FK_57 REFERENCES Environmental.carbon_offsetting_programs
)
USING DELTA;



-- ************************************** AncillaryRevenueTracking.SeatUpgrade
CREATE TABLE AncillaryRevenueTracking.SeatUpgrade
(
 UpgradeID   int NOT NULL CONSTRAINT PK_SeatUpgrade PRIMARY KEY,
 BookingID   int,
 OldSeat     string,
 NewSeat     string,
 UpgradeFee  decimal(10, 2),
 UpgradeDate timestamp,
 Reason      string,
 AncillaryID int NOT NULL CONSTRAINT FK_81 REFERENCES AncillaryRevenueTracking.AncillaryRevenue
);



-- ************************************** AncillaryRevenueTracking.Promotions
CREATE TABLE AncillaryRevenueTracking.Promotions
(
 PromotionID    int NOT NULL CONSTRAINT PK_Promotions PRIMARY KEY,
 PromotionName  string,
 Description    string,
 DiscountAmount decimal(10, 2),
 ValidFrom      timestamp,
 ValidUntil     timestamp,
 AncillaryID    int NOT NULL CONSTRAINT FK_83 REFERENCES AncillaryRevenueTracking.AncillaryRevenue
);



-- ************************************** AncillaryRevenueTracking.MealSelection
CREATE TABLE AncillaryRevenueTracking.MealSelection
(
 MealID         int NOT NULL CONSTRAINT PK_MealSelection PRIMARY KEY,
 AncillaryID    int CONSTRAINT FK_MealSelection_1 REFERENCES AncillaryRevenueTracking.AncillaryRevenue,
 MealType       string,
 Price          decimal(10, 2),
 SpecialRequest string
);



-- ************************************** AncillaryRevenueTracking.InsurancePurchase
CREATE TABLE AncillaryRevenueTracking.InsurancePurchase
(
 InsuranceID    int NOT NULL CONSTRAINT PK_InsurancePurchase PRIMARY KEY,
 AncillaryID    int CONSTRAINT FK_InsurancePurchase_1 REFERENCES AncillaryRevenueTracking.AncillaryRevenue,
 CoverageAmount decimal(10, 2),
 Premium        decimal(10, 2),
 Provider       string
);



-- ************************************** CustomerAnalytics.CustomerRetention
CREATE TABLE CustomerAnalytics.CustomerRetention
(
 RetentionID     int NOT NULL CONSTRAINT PK_CustomerRetention PRIMARY KEY,
 CustomerID      int CONSTRAINT FK_CustomerRetention_Customer REFERENCES CustomerProfile.Customer,
 RetentionDate   date,
 RetentionReason string,
 AnalysisID      int CONSTRAINT FK_CustomerRetention_Analysis REFERENCES CustomerAnalytics.FeedbackAnalysis
);



-- ************************************** AncillaryRevenueTracking.BaggageFee
CREATE TABLE AncillaryRevenueTracking.BaggageFee
(
 BaggageID     int NOT NULL CONSTRAINT PK_BaggageFee PRIMARY KEY,
 AncillaryID   int CONSTRAINT FK_BaggageFee_1 REFERENCES AncillaryRevenueTracking.AncillaryRevenue,
 BaggageType   string,
 Fee           decimal(10, 2),
 WeightLimit   int,
 PaymentStatus string
);



-- ************************************** AncillaryRevenueTracking.AncillaryRevenueReport
CREATE TABLE AncillaryRevenueTracking.AncillaryRevenueReport
(
 ReportID              int NOT NULL CONSTRAINT PK_AncillaryRevenueReport PRIMARY KEY,
 ReportDate            date,
 TotalAncillaryRevenue decimal(10, 2),
 AveragePerBooking     decimal(10, 2),
 TotalBookings         int,
 AncillaryID           int NOT NULL CONSTRAINT FK_82 REFERENCES AncillaryRevenueTracking.AncillaryRevenue
);



-- ************************************** AncillaryRevenue.ancillary_revenue_categories
CREATE TABLE AncillaryRevenue.ancillary_revenue_categories
(
 category_id   string NOT NULL CONSTRAINT PK_ancillary_revenue_categories PRIMARY KEY,
 category_name string NOT NULL,
 description   string,
 report_id     string NOT NULL CONSTRAINT FK_78 REFERENCES AncillaryRevenue.ancillary_revenue_reports
)
USING DELTA;



-- ************************************** Environmental.sustainability_initiatives
CREATE TABLE Environmental.sustainability_initiatives
(
 initiative_id   string NOT NULL CONSTRAINT PK_sustainability_initiatives PRIMARY KEY,
 goal_id         string NOT NULL CONSTRAINT FK_sustainability_initiatives_1 REFERENCES Environmental.sustainability_goals,
 initiative_name string NOT NULL,
 description     string,
 start_date      timestamp NOT NULL,
 end_date        timestamp,
 budget          decimal(10, 2) NOT NULL,
 status          string NOT NULL
)
USING DELTA;



-- ************************************** EsgData.esg_regulations
CREATE TABLE EsgData.esg_regulations
(
 regulation_id       string NOT NULL CONSTRAINT PK_esg_regulations PRIMARY KEY,
 regulation_name     string NOT NULL,
 description         string,
 effective_date      timestamp NOT NULL,
 jurisdiction        string NOT NULL,
 last_updated        timestamp NOT NULL,
 compliance_required boolean NOT NULL,
 assessment_id       string NOT NULL CONSTRAINT FK_64 REFERENCES EsgData.esg_risk_assessments
)
USING DELTA;



-- ************************************** EsgData.environmental_compliance
CREATE TABLE EsgData.environmental_compliance
(
 compliance_id     string NOT NULL CONSTRAINT PK_environmental_compliance PRIMARY KEY,
 regulation_id     string NOT NULL CONSTRAINT FK_environmental_compliance_1 REFERENCES EsgData.esg_regulations,
 compliance_status string NOT NULL,
 last_audit_date   timestamp,
 next_audit_date   timestamp,
 compliance_notes  string
)
USING DELTA;



-- ************************************** CustomerAnalytics.CustomerSegmentation
CREATE TABLE CustomerAnalytics.CustomerSegmentation
(
 SegmentID   int NOT NULL CONSTRAINT PK_CustomerSegmentation PRIMARY KEY,
 SegmentName string,
 Description string,
 Criteria    string,
 RetentionID int NOT NULL CONSTRAINT FK_55 REFERENCES CustomerAnalytics.CustomerRetention
);



-- ************************************** CustomerAnalytics.PersonalizationStrategy
CREATE TABLE CustomerAnalytics.PersonalizationStrategy
(
 StrategyID      int NOT NULL CONSTRAINT PK_PersonalizationStrategy PRIMARY KEY,
 StrategyName    string,
 Description     string,
 TargetSegmentID int CONSTRAINT FK_PersonalizationStrategy_Segment REFERENCES CustomerAnalytics.CustomerSegmentation
);



-- ************************************** EsgData.esg_risk_assessments
CREATE TABLE EsgData.esg_risk_assessments
(
 assessment_id       string NOT NULL CONSTRAINT PK_esg_risk_assessments PRIMARY KEY,
 assessment_date     timestamp NOT NULL,
 risk_description    string,
 risk_level          string NOT NULL,
 mitigation_strategy string,
 last_updated        timestamp NOT NULL,
 strategy_id         string CONSTRAINT FK_esg_risk_assessments_strategy REFERENCES EsgData.esg_strategy,
 report_id           string NOT NULL CONSTRAINT FK_63 REFERENCES EsgData.esg_reporting
)
USING DELTA;



-- ************************************** EsgData.esg_reporting
CREATE TABLE EsgData.esg_reporting
(
 report_id           string NOT NULL CONSTRAINT PK_esg_reporting PRIMARY KEY,
 report_date         timestamp NOT NULL,
 reporting_framework string NOT NULL CONSTRAINT FK_esg_reporting_framework REFERENCES EsgData.esg_reporting_frameworks,
 total_emissions     decimal(10, 2) NOT NULL,
 compliance_status   string NOT NULL,
 key_findings        string,
 recommendations     string,
 compliance_id       string NOT NULL CONSTRAINT FK_62 REFERENCES EsgData.environmental_compliance
)
USING DELTA;



-- ************************************** EsgData.esg_audit_findings
CREATE TABLE EsgData.esg_audit_findings
(
 finding_id          string NOT NULL CONSTRAINT PK_esg_audit_findings PRIMARY KEY,
 audit_date          timestamp NOT NULL,
 finding_description string,
 severity_level      string NOT NULL,
 action_plan         string,
 status              string NOT NULL,
 compliance_id       string CONSTRAINT FK_esg_audit_findings_compliance REFERENCES EsgData.environmental_compliance
)
USING DELTA;



-- ************************************** CustomerAnalytics.CampaignPerformance
CREATE TABLE CustomerAnalytics.CampaignPerformance
(
 CampaignID      int NOT NULL CONSTRAINT PK_CampaignPerformance PRIMARY KEY,
 CampaignName    string,
 StartDate       date,
 EndDate         date,
 TotalReach      int,
 EngagementRate  decimal(5, 2),
 TargetSegmentID int CONSTRAINT FK_CampaignPerformance_Segment REFERENCES CustomerAnalytics.CustomerSegmentation
);



-- ************************************** CustomerAnalytics.CustomerInteraction
CREATE TABLE CustomerAnalytics.CustomerInteraction
(
 InteractionID   int NOT NULL CONSTRAINT PK_CustomerInteraction PRIMARY KEY,
 CustomerID      int CONSTRAINT FK_CustomerInteraction_Customer REFERENCES CustomerProfile.Customer,
 InteractionType string,
 InteractionDate date,
 Outcome         string,
 CampaignID      int CONSTRAINT FK_CustomerInteraction_Campaign REFERENCES CustomerAnalytics.CampaignPerformance
);



-- ************************************** CustomerAnalytics.AnalyticsModels
CREATE TABLE CustomerAnalytics.AnalyticsModels
(
 ModelID         int NOT NULL CONSTRAINT PK_AnalyticsModels PRIMARY KEY,
 ModelName       string,
 Description     string,
 ModelType       string,
 Accuracy        decimal(5, 2),
 DateImplemented date,
 CampaignID      int CONSTRAINT FK_AnalyticsModels_Campaign REFERENCES CustomerAnalytics.CampaignPerformance
);

