-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- **************************************  SUPPLYCHAIN.PII
CREATE TAG SUPPLYCHAIN.PII ALLOWED_VALUES 'NO', 'YES';
