-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- **************************************  SUPPLYCHAIN.ACCESS_LEVEL
CREATE TAG SUPPLYCHAIN.ACCESS_LEVEL ALLOWED_VALUES 'RESTRICTED';
