-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.VIEW_1
CREATE VIEW ACMECORP.SUPPLYCHAIN.VIEW_1(
	MAINTENANCEID,
	MAINTENANCEDATE,
	MAINTENANCETYPE,
	MAINTENANCECOST,
	MAINTENANCEDURATIONHOURS,
	WAREHOUSEZONE,
	ZONEFUNCTION,
	WAREHOUSENAME,
	ADDRESS,
	CITY,
	STATE,
	COUNTRY
) COMMENT='View showing warehouse maintenance costs by zone and warehouse'
 as
(
  SELECT 
    wm.MaintenanceID,
    wm.DateKey AS MaintenanceDate,
    wm.MaintenanceType,
    wm.MaintenanceCost,
    wm.MaintenanceDurationHours,
    wz.ZoneName AS WarehouseZone,
    wz.ZoneFunction,
    w.WarehouseName,
    w.Address,
    w.City,
    w.State,
    w.Country
  FROM 
    WarehouseMaintenanceFact wm
  INNER JOIN Warehouse w
    ON wm.WarehouseKey = w.WarehouseID
  INNER JOIN WarehouseZoneDim wz
    ON w.WarehouseID = wz.WarehouseKey
);
