-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.WAREHOUSE
CREATE TABLE SUPPLYCHAIN.WAREHOUSE
(
 WAREHOUSEID   number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''WarehouseID'''' column contains data related to ''''warehouseid''''. This column likely represents an identifier.',
 WAREHOUSENAME varchar(255) NOT NULL COMMENT 'The ''''WarehouseName'''' column contains data related to ''''warehousename''''. This column holds name-related data.',
 ADDRESS       varchar(255) COMMENT 'The ''''Address'''' column contains data related to ''''address''''.',
 CITY          varchar(100) COMMENT 'The ''''City'''' column contains data related to ''''city''''.',
 STATE         varchar(100) COMMENT 'The ''''State'''' column contains data related to ''''state''''.',
 ZIPCODE       varchar(20) COMMENT 'The ''''ZipCode'''' column contains data related to ''''zipcode''''.',
 COUNTRY       varchar(100) COMMENT 'The ''''Country'''' column contains data related to ''''country''''.',
 MANAGERNAME   varchar(255) COMMENT 'The ''''ManagerName'''' column contains data related to ''''managername''''. This column holds name-related data.',
 CAPACITY      number(38,0) COMMENT 'The ''''Capacity'''' column contains data related to ''''capacity''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( WAREHOUSEID )
) WITH TAG (SUPPLYCHAIN.RETENTION_PERIOD = '7 YEARS');
