-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.ORDERCANCELLATIONREASONDIM
CREATE TABLE SUPPLYCHAIN.ORDERCANCELLATIONREASONDIM
(
 CANCELLATIONREASONKEY number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''CancellationReasonKey'''' column contains data related to ''''cancellationreasonkey''''.',
 REASONDESCRIPTION     varchar(255) NOT NULL COMMENT 'The ''''ReasonDescription'''' column contains data related to ''''reasondescription''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( CANCELLATIONREASONKEY )
);
