-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.ORDERRETURNSPOLICYDIM
CREATE TABLE SUPPLYCHAIN.ORDERRETURNSPOLICYDIM
(
 RETURNSPOLICYKEY  number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''ReturnsPolicyKey'''' column contains data related to ''''returnspolicykey''''.',
 POLICYDESCRIPTION varchar(255) COMMENT 'The ''''PolicyDescription'''' column contains data related to ''''policydescription''''.',
 RETURNWINDOWDAYS  number(38,0) COMMENT 'The ''''ReturnWindowDays'''' column contains data related to ''''returnwindowdays''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( RETURNSPOLICYKEY )
);
