-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.CUSTOMERPAYMENTS
CREATE TABLE SUPPLYCHAIN.CUSTOMERPAYMENTS
(
 PAYMENTDATE      date NOT NULL COMMENT 'The ''''PaymentDate'''' column contains data related to ''''paymentdate''''. This column stores information related to dates or times.',
 AMOUNT           number(15,2) NOT NULL COMMENT 'The ''''Amount'''' column contains data related to ''''amount''''. This column represents a numeric value, likely related to amounts or prices.',
 PAYMENTMETHOD    varchar(50) COMMENT 'The ''''PaymentMethod'''' column contains data related to ''''paymentmethod''''.',
 PAYMENTREFERENCE varchar(100) COMMENT 'The ''''PaymentReference'''' column contains data related to ''''paymentreference''''.',
 CUSTOMERID       number(38,0) NOT NULL COMMENT 'The ''''CustomerID'''' column contains data related to ''''customerid''''. This column likely represents an identifier.',
 PAYMENTID        number(38,0) NOT NULL COMMENT 'The ''''PaymentID'''' column contains data related to ''''paymentid''''. This column likely represents an identifier.',

 CONSTRAINT FK_17 FOREIGN KEY ( PAYMENTID ) REFERENCES SUPPLYCHAIN.SUPPLIERPAYMENTS ( PAYMENTID ),
 CONSTRAINT FK_7 FOREIGN KEY ( CUSTOMERID ) REFERENCES SUPPLYCHAIN.CUSTOMER ( CUSTOMERID )
);
