-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.PRODUCTLIFECYCLEDIM
CREATE TABLE SUPPLYCHAIN.PRODUCTLIFECYCLEDIM
(
 LIFECYCLEKEY       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''LifecycleKey'''' column contains data related to ''''lifecyclekey''''.',
 PRODUCTKEY         number(38,0) COMMENT 'The ''''ProductKey'''' column contains data related to ''''productkey''''.',
 LIFECYCLESTAGE     varchar(50) COMMENT 'The ''''LifecycleStage'''' column contains data related to ''''lifecyclestage''''.',
 EFFECTIVESTARTDATE date COMMENT 'The ''''EffectiveStartDate'''' column contains data related to ''''effectivestartdate''''. This column stores information related to dates or times.',
 EFFECTIVEENDDATE   date COMMENT 'The ''''EffectiveEndDate'''' column contains data related to ''''effectiveenddate''''. This column stores information related to dates or times.',

 CONSTRAINT PK_1 PRIMARY KEY ( LIFECYCLEKEY )
);
