-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.CATEGORYDIM
CREATE TABLE SUPPLYCHAIN.CATEGORYDIM
(
 CATEGORYKEY  number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''CategoryKey'''' column contains data related to ''''categorykey''''.',
 CATEGORYNAME varchar(255) NOT NULL COMMENT 'The ''''CategoryName'''' column contains data related to ''''categoryname''''. This column holds name-related data.',
 DESCRIPTION  varchar(500) COMMENT 'The ''''Description'''' column contains data related to ''''description''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( CATEGORYKEY )
);
