-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.PRODUCTRETURNFACT
CREATE TABLE SUPPLYCHAIN.PRODUCTRETURNFACT
(
 RETURNID         number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''ReturnID'''' column contains data related to ''''returnid''''. This column likely represents an identifier.',
 ORDERID          number(38,0) NOT NULL COMMENT 'The ''''OrderID'''' column contains data related to ''''orderid''''. This column likely represents an identifier.',
 PRODUCTKEY       number(38,0) COMMENT 'The ''''ProductKey'''' column contains data related to ''''productkey''''.',
 DATEKEY          date COMMENT 'The ''''DateKey'''' column contains data related to ''''datekey''''. This column stores information related to dates or times.',
 QUANTITYRETURNED number(38,0) COMMENT 'The ''''QuantityReturned'''' column contains data related to ''''quantityreturned''''.',
 RETURNREASON     varchar(255) COMMENT 'The ''''ReturnReason'''' column contains data related to ''''returnreason''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( RETURNID ),
 CONSTRAINT FK_14 FOREIGN KEY ( ORDERID ) REFERENCES SUPPLYCHAIN.ORDERS ( ORDERID )
);
