-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.USERDIM
CREATE TABLE SUPPLYCHAIN.USERDIM
(
 USERID    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''UserID'''' column contains data related to ''''userid''''. This column likely represents an identifier.',
 FIRSTNAME varchar(100) COMMENT 'The ''''FirstName'''' column contains data related to ''''firstname''''. This column holds name-related data.',
 LASTNAME  varchar(100) COMMENT 'The ''''LastName'''' column contains data related to ''''lastname''''. This column holds name-related data.',
 EMAIL     varchar(255) COMMENT 'The ''''Email'''' column contains data related to ''''email''''.',
 ROLE      varchar(50) COMMENT 'The ''''Role'''' column contains data related to ''''role''''.',
 HIREDATE  date COMMENT 'The ''''HireDate'''' column contains data related to ''''hiredate''''. This column stores information related to dates or times.',

 CONSTRAINT PK_1 PRIMARY KEY ( USERID )
);
