-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.PRICINGDIM
CREATE TABLE SUPPLYCHAIN.PRICINGDIM
(
 PRICINGKEY         number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''PricingKey'''' column contains data related to ''''pricingkey''''.',
 PRODUCTKEY         number(38,0) COMMENT 'The ''''ProductKey'''' column contains data related to ''''productkey''''.',
 CUSTOMERKEY        number(38,0) COMMENT 'The ''''CustomerKey'''' column contains data related to ''''customerkey''''.',
 PRICETIER          varchar(50) COMMENT 'The ''''PriceTier'''' column contains data related to ''''pricetier''''. This column represents a numeric value, likely related to amounts or prices.',
 UNITPRICE          number(10,2) COMMENT 'The ''''UnitPrice'''' column contains data related to ''''unitprice''''. This column represents a numeric value, likely related to amounts or prices.',
 EFFECTIVESTARTDATE date COMMENT 'The ''''EffectiveStartDate'''' column contains data related to ''''effectivestartdate''''. This column stores information related to dates or times.',
 EFFECTIVEENDDATE   date COMMENT 'The ''''EffectiveEndDate'''' column contains data related to ''''effectiveenddate''''. This column stores information related to dates or times.',

 CONSTRAINT PK_1 PRIMARY KEY ( PRICINGKEY )
);
