-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.WAREHOUSEOPERATIONSFACT
CREATE TABLE SUPPLYCHAIN.WAREHOUSEOPERATIONSFACT
(
 WAREHOUSEOPERATIONID   number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The unique identifier for warehouse operation.',
 WAREHOUSEKEY           number(38,0) COMMENT 'References the warehouse in the WarehouseDim table.',
 ZONEKEY                number(38,0) COMMENT 'References the zone in the WarehouseZoneDim table.',
 VEHICLEKEY             number(38,0) COMMENT 'References the vehicle in the TransportVehicleDim table.',
 DATEKEY                date COMMENT 'Date of the operation.',
 TOTALMAINTENANCECOST   number(10,2) COMMENT 'Total maintenance cost for the warehouse on a given day.',
 ENERGYCONSUMEDKWH      number(10,2) COMMENT 'Total energy consumption for the warehouse on a given day.',
 VEHICLEUSAGEHOURS      number(5,2) COMMENT 'Total vehicle usage hours for the warehouse on a given day.',
 TOTALEMPLOYEESINVOLVED number(38,0) COMMENT 'Number of employees involved in warehouse operations on a given day.',
 TASKSCOMPLETED         number(38,0) COMMENT 'Total number of tasks completed in the warehouse on a given day.',

 CONSTRAINT PK_WAREHOUSEOPERATIONSFACT PRIMARY KEY ( WAREHOUSEOPERATIONID ),
 CONSTRAINT FK_DATEKEY FOREIGN KEY ( DATEKEY ) REFERENCES SUPPLYCHAIN.DATEDIM ( DATEKEY ),
 CONSTRAINT FK_VEHICLEKEY FOREIGN KEY ( VEHICLEKEY ) REFERENCES SUPPLYCHAIN.TRANSPORTVEHICLEDIM ( VEHICLEKEY ),
 CONSTRAINT FK_WAREHOUSEKEY FOREIGN KEY ( WAREHOUSEKEY ) REFERENCES SUPPLYCHAIN.WAREHOUSE ( WAREHOUSEID ),
 CONSTRAINT FK_ZONEKEY FOREIGN KEY ( ZONEKEY ) REFERENCES SUPPLYCHAIN.WAREHOUSEZONEDIM ( ZONEKEY )
)
COMMENT = 'This table is designed to provide detailed information about each date, including breakdowns of years, months, weeks, and more. This is commonly used in data warehouses for time-based analysis.';
