-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.WAREHOUSEZONEDIM
CREATE TABLE SUPPLYCHAIN.WAREHOUSEZONEDIM
(
 ZONEKEY      number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''ZoneKey'''' column contains data related to ''''zonekey''''.',
 WAREHOUSEKEY number(38,0) COMMENT 'The ''''WarehouseKey'''' column contains data related to ''''warehousekey''''.',
 ZONENAME     varchar(100) COMMENT 'The ''''ZoneName'''' column contains data related to ''''zonename''''. This column holds name-related data.',
 ZONEFUNCTION varchar(100) COMMENT 'The ''''ZoneFunction'''' column contains data related to ''''zonefunction''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( ZONEKEY )
);
