-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.SUPPLIERRELATIONSHIPDIM
CREATE TABLE SUPPLYCHAIN.SUPPLIERRELATIONSHIPDIM
(
 SUPPLIERRELATIONSHIPKEY number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''SupplierRelationshipKey'''' column contains data related to ''''supplierrelationshipkey''''.',
 SUPPLIERKEY             number(38,0) COMMENT 'The ''''SupplierKey'''' column contains data related to ''''supplierkey''''.',
 RELATIONSHIPTYPE        varchar(50) COMMENT 'The ''''RelationshipType'''' column contains data related to ''''relationshiptype''''.',
 AGREEMENTDETAILS        varchar(500) COMMENT 'The ''''AgreementDetails'''' column contains data related to ''''agreementdetails''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( SUPPLIERRELATIONSHIPKEY )
);
