-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.DATEDIM
CREATE TABLE SUPPLYCHAIN.DATEDIM
(
 DATEKEY            date NOT NULL COMMENT 'Primary key for the date dimension, usually in YYYY-MM-DD format.',
 FULLDATE           date COMMENT 'The full date value.',
 DAY                number(38,0) COMMENT 'Day of the month (1-31).',
 DAYSUFFIX          varchar(4) COMMENT 'Suffix for the day (st, nd, rd, th).',
 DAYNAME            varchar(10) COMMENT 'Name of the day (Monday, Tuesday, etc.).',
 WEEKDAYWEEKENDFLAG varchar(10) COMMENT 'Indicates whether the date is a weekday or weekend.',
 ISHOLIDAY          boolean COMMENT 'Indicates if the date is a holiday (true/false).',
 WEEKNUMBEROFYEAR   number(38,0) COMMENT 'The week number of the year.',
 MONTH              number(38,0) COMMENT 'Month number (1-12).',
 MONTHNAME          varchar(20) COMMENT 'Full name of the month (January, February, etc.).',
 QUARTER            number(38,0) COMMENT 'Quarter of the year (1-4).',
 QUARTERNAME        varchar(20) COMMENT 'Full name of the quarter (Q1, Q2, Q3, Q4).',
 YEAR               number(38,0) COMMENT 'The full year (e.g., 2023).',
 FISCALYEAR         number(38,0) COMMENT 'Fiscal year associated with the date.',
 FISCALQUARTER      number(38,0) COMMENT 'Fiscal quarter (1-4).',
 FISCALMONTH        number(38,0) COMMENT 'Fiscal month (1-12).',
 ISWEEKEND          boolean COMMENT 'Indicates if the date is on a weekend (true/false).',
 ISWORKDAY          boolean COMMENT 'Indicates if the date is a working day (true/false).',

 CONSTRAINT DATEKEY PRIMARY KEY ( DATEKEY )
)
COMMENT = 'Date dimension table for time-related analysis';
