-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.INVENTORY
CREATE TABLE SUPPLYCHAIN.INVENTORY
(
 INVENTORYID number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''InventoryID'''' column contains data related to ''''inventoryid''''. This column likely represents an identifier.',
 QUANTITY    number(38,0) NOT NULL COMMENT 'The ''''Quantity'''' column contains data related to ''''quantity''''.',
 LASTUPDATED date DEFAULT CURRENT_DATE() COMMENT 'The ''''LastUpdated'''' column contains data related to ''''lastupdated''''. This column stores information related to dates or times.',
 PRODUCTID   number(38,0) NOT NULL,
 WAREHOUSEID number(38,0) NOT NULL,

 CONSTRAINT PK_1 PRIMARY KEY ( INVENTORYID )
) WITH TAG (SUPPLYCHAIN.DATA_OWNER = 'SUPPLYCHAINTEAM');
