-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.AUDITLOGFACT
CREATE TABLE SUPPLYCHAIN.AUDITLOGFACT
(
 USERID         number(38,0) NOT NULL COMMENT 'The ''''UserID'''' column contains data related to ''''userid''''. This column likely represents an identifier.',
 AUDITID        number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''AuditID'''' column contains data related to ''''auditid''''. This column likely represents an identifier.',
 ACTION         varchar(255) COMMENT 'The ''''Action'''' column contains data related to ''''action''''.',
 ACTIONDATE     date COMMENT 'The ''''ActionDate'''' column contains data related to ''''actiondate''''. This column stores information related to dates or times.',
 ACTIONTIME     timestamp_ntz(9) COMMENT 'The ''''ActionTime'''' column contains data related to ''''actiontime''''. This column stores information related to dates or times.',
 ENTITYAFFECTED varchar(100) COMMENT 'The ''''EntityAffected'''' column contains data related to ''''entityaffected''''.',
 ENTITYID       number(38,0) COMMENT 'The ''''EntityID'''' column contains data related to ''''entityid''''. This column likely represents an identifier.',
 NOTES          varchar(500) COMMENT 'The ''''Notes'''' column contains data related to ''''notes''''.',

 CONSTRAINT FK_18 FOREIGN KEY ( USERID ) REFERENCES SUPPLYCHAIN.USERDIM ( USERID )
) WITH TAG (SUPPLYCHAIN.ACCESS_LEVEL = 'RESTRICTED');
