-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.QUALITYCONTROLFACT
CREATE TABLE SUPPLYCHAIN.QUALITYCONTROLFACT
(
 QCID             number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''QCID'''' column contains data related to ''''qcid''''. This column likely represents an identifier.',
 PRODUCTKEY       number(38,0) COMMENT 'The ''''ProductKey'''' column contains data related to ''''productkey''''.',
 SUPPLIERKEY      number(38,0) COMMENT 'The ''''SupplierKey'''' column contains data related to ''''supplierkey''''.',
 DATEKEY          date COMMENT 'The ''''DateKey'''' column contains data related to ''''datekey''''. This column stores information related to dates or times.',
 QUANTITYCHECKED  number(38,0) COMMENT 'The ''''QuantityChecked'''' column contains data related to ''''quantitychecked''''.',
 QUANTITYREJECTED number(38,0) COMMENT 'The ''''QuantityRejected'''' column contains data related to ''''quantityrejected''''.',
 QCNOTES          varchar(500) COMMENT 'The ''''QCNotes'''' column contains data related to ''''qcnotes''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( QCID )
);
