-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.EMPLOYEEDIM
CREATE TABLE SUPPLYCHAIN.EMPLOYEEDIM
(
 EMPLOYEEKEY     number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''EmployeeKey'''' column contains data related to ''''employeekey''''.',
 EMPLOYEEID      number(38,0) COMMENT 'The ''''EmployeeID'''' column contains data related to ''''employeeid''''. This column likely represents an identifier.',
 FIRSTNAME       varchar(100) COMMENT 'The ''''FirstName'''' column contains data related to ''''firstname''''. This column holds name-related data.',
 LASTNAME        varchar(100) COMMENT 'The ''''LastName'''' column contains data related to ''''lastname''''. This column holds name-related data.',
 JOBTITLE        varchar(100) COMMENT 'The ''''JobTitle'''' column contains data related to ''''jobtitle''''.',
 DEPARTMENT      varchar(100) COMMENT 'The ''''Department'''' column contains data related to ''''department''''.',
 HIREDATE        date COMMENT 'The ''''HireDate'''' column contains data related to ''''hiredate''''. This column stores information related to dates or times.',
 TERMINATIONDATE date COMMENT 'The ''''TerminationDate'''' column contains data related to ''''terminationdate''''. This column stores information related to dates or times.',
 SUPERVISORID    number(38,0) COMMENT 'The ''''SupervisorID'''' column contains data related to ''''supervisorid''''. This column likely represents an identifier.'
);
