-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.ORDERSTATUSDIM
CREATE TABLE SUPPLYCHAIN.ORDERSTATUSDIM
(
 ORDERSTATUSKEY    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''OrderStatusKey'''' column contains data related to ''''orderstatuskey''''. This column contains status information.',
 STATUSDESCRIPTION varchar(255) NOT NULL COMMENT 'The ''''StatusDescription'''' column contains data related to ''''statusdescription''''. This column contains status information.',

 CONSTRAINT PK_1 PRIMARY KEY ( ORDERSTATUSKEY )
);
