-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.CUSTOMERLOYALTYPROGRAMDIM
CREATE TABLE SUPPLYCHAIN.CUSTOMERLOYALTYPROGRAMDIM
(
 LOYALTYPROGRAMKEY number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''LoyaltyProgramKey'''' column contains data related to ''''loyaltyprogramkey''''.',
 CUSTOMERKEY       number(38,0) COMMENT 'The ''''CustomerKey'''' column contains data related to ''''customerkey''''.',
 PROGRAMNAME       varchar(100) COMMENT 'The ''''ProgramName'''' column contains data related to ''''programname''''. This column holds name-related data.',
 REWARDPOINTS      number(38,0) COMMENT 'The ''''RewardPoints'''' column contains data related to ''''rewardpoints''''.',
 PROGRAMSTARTDATE  date COMMENT 'The ''''ProgramStartDate'''' column contains data related to ''''programstartdate''''. This column stores information related to dates or times.',

 CONSTRAINT PK_1 PRIMARY KEY ( LOYALTYPROGRAMKEY )
);
