-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.SHIPPINGINCIDENTFACT
CREATE TABLE SUPPLYCHAIN.SHIPPINGINCIDENTFACT
(
 INCIDENTID     number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''IncidentID'''' column contains data related to ''''incidentid''''. This column likely represents an identifier.',
 ZONEKEY        number(38,0) NOT NULL COMMENT 'The ''''ZoneKey'''' column contains data related to ''''zonekey''''.',
 ORDERSTATUSKEY number(38,0) NOT NULL COMMENT 'The ''''OrderStatusKey'''' column contains data related to ''''orderstatuskey''''. This column contains status information.',
 SHIPMENTID     number(38,0) NOT NULL COMMENT 'The ''''ShipmentID'''' column contains data related to ''''shipmentid''''. This column likely represents an identifier.',
 DATEKEY        date COMMENT 'The ''''DateKey'''' column contains data related to ''''datekey''''. This column stores information related to dates or times.',
 INCIDENTTYPE   varchar(50) COMMENT 'The ''''IncidentType'''' column contains data related to ''''incidenttype''''. This column likely represents an identifier.',
 RESOLUTION     varchar(255) COMMENT 'The ''''Resolution'''' column contains data related to ''''resolution''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( INCIDENTID, ZONEKEY, ORDERSTATUSKEY ),
 CONSTRAINT FK_2 FOREIGN KEY ( ZONEKEY ) REFERENCES SUPPLYCHAIN.WAREHOUSEZONEDIM ( ZONEKEY ),
 CONSTRAINT FK_3 FOREIGN KEY ( ORDERSTATUSKEY ) REFERENCES SUPPLYCHAIN.ORDERSTATUSDIM ( ORDERSTATUSKEY ),
 CONSTRAINT FK_8 FOREIGN KEY ( SHIPMENTID ) REFERENCES SUPPLYCHAIN.SHIPMENT ( SHIPMENTID )
);
