-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.PRODUCT
CREATE TABLE SUPPLYCHAIN.PRODUCT
(
 PRODUCTID    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''ProductID'''' column contains data related to ''''productid''''. This column likely represents an identifier.',
 SUPPLIERID   number(38,0) NOT NULL COMMENT 'The ''''SupplierID'''' column contains data related to ''''supplierid''''. This column likely represents an identifier.',
 PRODUCTNAME  varchar(255) NOT NULL COMMENT 'The ''''ProductName'''' column contains data related to ''''productname''''. This column holds name-related data.',
 CATEGORY     varchar(100) COMMENT 'The ''''Category'''' column contains data related to ''''category''''.',
 UNITPRICE    number(10,2) COMMENT 'The ''''UnitPrice'''' column contains data related to ''''unitprice''''. This column represents a numeric value, likely related to amounts or prices.',
 UNITSINSTOCK number(38,0) COMMENT 'The ''''UnitsInStock'''' column contains data related to ''''unitsinstock''''.',
 UNITSONORDER number(38,0) COMMENT 'The ''''UnitsOnOrder'''' column contains data related to ''''unitsonorder''''.',
 REORDERLEVEL number(38,0) COMMENT 'The ''''ReorderLevel'''' column contains data related to ''''reorderlevel''''.',
 DISCONTINUED boolean DEFAULT FALSE COMMENT 'The ''''Discontinued'''' column contains data related to ''''discontinued''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( PRODUCTID ),
 CONSTRAINT FK_12 FOREIGN KEY ( SUPPLIERID ) REFERENCES SUPPLYCHAIN.SUPPLIER ( SUPPLIERID )
);
