-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.INVENTORYSHRINKAGEFACT
CREATE TABLE SUPPLYCHAIN.INVENTORYSHRINKAGEFACT
(
 SHRINKAGEID       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''ShrinkageID'''' column contains data related to ''''shrinkageid''''. This column likely represents an identifier.',
 PRODUCTKEY        number(38,0) COMMENT 'The ''''ProductKey'''' column contains data related to ''''productkey''''.',
 WAREHOUSEKEY      number(38,0) COMMENT 'The ''''WarehouseKey'''' column contains data related to ''''warehousekey''''.',
 DATEKEY           date COMMENT 'The ''''DateKey'''' column contains data related to ''''datekey''''. This column stores information related to dates or times.',
 SHRINKAGEQUANTITY number(38,0) COMMENT 'The ''''ShrinkageQuantity'''' column contains data related to ''''shrinkagequantity''''.',
 SHRINKAGEREASON   varchar(255) COMMENT 'The ''''ShrinkageReason'''' column contains data related to ''''shrinkagereason''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( SHRINKAGEID )
);
