-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.FORECASTINGFACT
CREATE TABLE SUPPLYCHAIN.FORECASTINGFACT
(
 FORECASTID       number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''ForecastID'''' column contains data related to ''''forecastid''''. This column likely represents an identifier.',
 SHRINKAGEID      number(38,0) NOT NULL COMMENT 'The ''''ShrinkageID'''' column contains data related to ''''shrinkageid''''. This column likely represents an identifier.',
 PRODUCTKEY       number(38,0) COMMENT 'The ''''ProductKey'''' column contains data related to ''''productkey''''.',
 DATEKEY          date COMMENT 'The ''''DateKey'''' column contains data related to ''''datekey''''. This column stores information related to dates or times.',
 WAREHOUSEKEY     number(38,0) COMMENT 'The ''''WarehouseKey'''' column contains data related to ''''warehousekey''''.',
 FORECASTEDDEMAND number(38,0) COMMENT 'The ''''ForecastedDemand'''' column contains data related to ''''forecasteddemand''''.',
 ACTUALDEMAND     number(38,0) COMMENT 'The ''''ActualDemand'''' column contains data related to ''''actualdemand''''.',
 FORECASTACCURACY number(5,2) COMMENT 'The ''''ForecastAccuracy'''' column contains data related to ''''forecastaccuracy''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( FORECASTID, SHRINKAGEID ),
 CONSTRAINT FK_1 FOREIGN KEY ( SHRINKAGEID ) REFERENCES SUPPLYCHAIN.INVENTORYSHRINKAGEFACT ( SHRINKAGEID )
);
