-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.SHIPMENT
CREATE TABLE SUPPLYCHAIN.SHIPMENT
(
 SHIPMENTID          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''ShipmentID'''' column contains data related to ''''shipmentid''''. This column likely represents an identifier.',
 WAREHOUSEID         number(38,0) NOT NULL COMMENT 'The ''''WarehouseID'''' column contains data related to ''''warehouseid''''. This column likely represents an identifier.',
 SHIPMENTDATE        date NOT NULL COMMENT 'The ''''ShipmentDate'''' column contains data related to ''''shipmentdate''''. This column stores information related to dates or times.',
 EXPECTEDARRIVALDATE date COMMENT 'The ''''ExpectedArrivalDate'''' column contains data related to ''''expectedarrivaldate''''. This column stores information related to dates or times.',
 SHIPMENTSTATUS      varchar(50) COMMENT 'The ''''ShipmentStatus'''' column contains data related to ''''shipmentstatus''''. This column contains status information.',
 SHIPPINGCARRIER     varchar(100) COMMENT 'The ''''ShippingCarrier'''' column contains data related to ''''shippingcarrier''''.',
 TRACKINGNUMBER      varchar(50) COMMENT 'The ''''TrackingNumber'''' column contains data related to ''''trackingnumber''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( SHIPMENTID ),
 CONSTRAINT FK_9 FOREIGN KEY ( WAREHOUSEID ) REFERENCES SUPPLYCHAIN.WAREHOUSE ( WAREHOUSEID )
);
