-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.SUPPLIERRISKASSESSMENTFACT
CREATE TABLE SUPPLYCHAIN.SUPPLIERRISKASSESSMENTFACT
(
 ASSESSMENTID    number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''AssessmentID'''' column contains data related to ''''assessmentid''''. This column likely represents an identifier.',
 SUPPLIERKEY     number(38,0) COMMENT 'The ''''SupplierKey'''' column contains data related to ''''supplierkey''''.',
 DATEKEY         date COMMENT 'The ''''DateKey'''' column contains data related to ''''datekey''''. This column stores information related to dates or times.',
 RISKLEVEL       varchar(50) COMMENT 'The ''''RiskLevel'''' column contains data related to ''''risklevel''''.',
 ASSESSMENTNOTES varchar(500) COMMENT 'The ''''AssessmentNotes'''' column contains data related to ''''assessmentnotes''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( ASSESSMENTID )
);
