-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.SUPPLIERPERFORMANCEFACT
CREATE TABLE SUPPLYCHAIN.SUPPLIERPERFORMANCEFACT
(
 SUPPLIERPERFORMANCEFACTID number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''SupplierPerformanceFactID'''' column contains data related to ''''supplierperformancefactid''''. This column likely represents an identifier.',
 SUPPLIERKEY               number(38,0) COMMENT 'The ''''SupplierKey'''' column contains data related to ''''supplierkey''''.',
 DATEKEY                   date COMMENT 'The ''''DateKey'''' column contains data related to ''''datekey''''. This column stores information related to dates or times.',
 LEADTIME                  number(38,0) COMMENT 'The ''''LeadTime'''' column contains data related to ''''leadtime''''. This column stores information related to dates or times.',
 DEFECTRATE                number(5,2) COMMENT 'The ''''DefectRate'''' column contains data related to ''''defectrate''''.',
 ONTIMEDELIVERYRATE        number(5,2) COMMENT 'The ''''OnTimeDeliveryRate'''' column contains data related to ''''ontimedeliveryrate''''. This column stores information related to dates or times.',

 CONSTRAINT PK_1 PRIMARY KEY ( SUPPLIERPERFORMANCEFACTID )
);
