-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.ENERGYCONSUMPTIONFACT
CREATE TABLE SUPPLYCHAIN.ENERGYCONSUMPTIONFACT
(
 ENERGYID          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''EnergyID'''' column contains data related to ''''energyid''''. This column likely represents an identifier.',
 WAREHOUSEKEY      number(38,0) COMMENT 'The ''''WarehouseKey'''' column contains data related to ''''warehousekey''''.',
 DATEKEY           date COMMENT 'The ''''DateKey'''' column contains data related to ''''datekey''''. This column stores information related to dates or times.',
 ENERGYCONSUMEDKWH number(10,2) COMMENT 'The ''''EnergyConsumedKWh'''' column contains data related to ''''energyconsumedkwh''''.',
 ENERGYCOST        number(10,2) COMMENT 'The ''''EnergyCost'''' column contains data related to ''''energycost''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( ENERGYID )
);
