-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.SUPPLIERPAYMENTS
CREATE TABLE SUPPLYCHAIN.SUPPLIERPAYMENTS
(
 PAYMENTID        number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''PaymentID'''' column contains data related to ''''paymentid''''. This column likely represents an identifier.',
 PAYMENTDATE      date NOT NULL COMMENT 'The ''''PaymentDate'''' column contains data related to ''''paymentdate''''. This column stores information related to dates or times.',
 AMOUNT           number(15,2) NOT NULL COMMENT 'The ''''Amount'''' column contains data related to ''''amount''''. This column represents a numeric value, likely related to amounts or prices.',
 PAYMENTMETHOD    varchar(50) COMMENT 'The ''''PaymentMethod'''' column contains data related to ''''paymentmethod''''.',
 PAYMENTREFERENCE varchar(100) COMMENT 'The ''''PaymentReference'''' column contains data related to ''''paymentreference''''.',
 SUPPLIERID       number(38,0) NOT NULL COMMENT 'The ''''SupplierID'''' column contains data related to ''''supplierid''''. This column likely represents an identifier.',

 CONSTRAINT PK_1 PRIMARY KEY ( PAYMENTID ),
 CONSTRAINT FK_15 FOREIGN KEY ( SUPPLIERID ) REFERENCES SUPPLYCHAIN.SUPPLIER ( SUPPLIERID )
) WITH TAG (SUPPLYCHAIN.ACCESS_LEVEL = 'RESTRICTED');
