-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.CUSTOMER
CREATE TABLE SUPPLYCHAIN.CUSTOMER
(
 CUSTOMERID   number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''CustomerID'''' column contains data related to ''''customerid''''. This column likely represents an identifier.',
 CUSTOMERNAME varchar(255) NOT NULL WITH TAG (SUPPLYCHAIN.PII = 'YES') COMMENT 'The ''''CustomerName'''' column contains data related to ''''customername''''. This column holds name-related data.',
 CONTACTNAME  varchar(255) COMMENT 'The ''''ContactName'''' column contains data related to ''''contactname''''. This column holds name-related data.',
 CONTACTTITLE varchar(255) COMMENT 'The ''''ContactTitle'''' column contains data related to ''''contacttitle''''.',
 ADDRESS      varchar(255) COMMENT 'The ''''Address'''' column contains data related to ''''address''''.',
 CITY         varchar(100) COMMENT 'The ''''City'''' column contains data related to ''''city''''.',
 STATE        varchar(100) COMMENT 'The ''''State'''' column contains data related to ''''state''''.',
 ZIPCODE      varchar(20) COMMENT 'The ''''ZipCode'''' column contains data related to ''''zipcode''''.',
 COUNTRY      varchar(100) COMMENT 'The ''''Country'''' column contains data related to ''''country''''.',
 PHONE        varchar(20) COMMENT 'The ''''Phone'''' column contains data related to ''''phone''''.',
 EMAIL        varchar(100) COMMENT 'The ''''Email'''' column contains data related to ''''email''''.',
 CUSTOMERTYPE varchar(100) COMMENT 'The ''''CustomerType'''' column contains data related to ''''customertype''''.',

 CONSTRAINT PK_1 PRIMARY KEY ( CUSTOMERID )
) WITH TAG (SUPPLYCHAIN.PII = 'YES');
