-- ************************** SqlDBM: Snowflake *************************
-- *** Generated by SqlDBM: Untitled project by hazal.sener@sqldbm.com **

-- ************************************** SUPPLYCHAIN.ORDERSTATUSTRANSITIONFACT
CREATE TABLE SUPPLYCHAIN.ORDERSTATUSTRANSITIONFACT
(
 TRANSITIONID          number(38,0) NOT NULL AUTOINCREMENT START 1 INCREMENT 1 COMMENT 'The ''''TransitionID'''' column contains data related to ''''transitionid''''. This column likely represents an identifier.',
 CANCELLATIONREASONKEY number(38,0) NOT NULL COMMENT 'The ''''CancellationReasonKey'''' column contains data related to ''''cancellationreasonkey''''.',
 ORDERID               number(38,0) NOT NULL COMMENT 'The ''''OrderID'''' column contains data related to ''''orderid''''. This column likely represents an identifier.',
 OLDSTATUSKEY          number(38,0) COMMENT 'The ''''OldStatusKey'''' column contains data related to ''''oldstatuskey''''. This column contains status information.',
 NEWSTATUSKEY          number(38,0) COMMENT 'The ''''NewStatusKey'''' column contains data related to ''''newstatuskey''''. This column contains status information.',
 TRANSITIONDATE        date COMMENT 'The ''''TransitionDate'''' column contains data related to ''''transitiondate''''. This column stores information related to dates or times.',
 TRANSITIONTIME        timestamp_ntz(9) COMMENT 'The ''''TransitionTime'''' column contains data related to ''''transitiontime''''. This column stores information related to dates or times.',

 CONSTRAINT PK_1 PRIMARY KEY ( TRANSITIONID, CANCELLATIONREASONKEY ),
 CONSTRAINT FK_4 FOREIGN KEY ( CANCELLATIONREASONKEY ) REFERENCES SUPPLYCHAIN.ORDERCANCELLATIONREASONDIM ( CANCELLATIONREASONKEY ),
 CONSTRAINT FK_5 FOREIGN KEY ( ORDERID ) REFERENCES SUPPLYCHAIN.ORDERS ( ORDERID )
) WITH TAG (SUPPLYCHAIN.RETENTION_PERIOD = '7 YEARS');
